### PR TITLE
Allow deny votes

### PR DESCRIPTION
**Pull request by RedSparr0w**
#8 
- [x] Rejection at 3 votes
- [x] Contested (those having both an accept or rejection) submissions must be resolved by a Shiny Verifier
- [x] Add points for denied posts
- [x]  List of contested submissions for review

### CODE REVIEW

**Comment by RedSparr0w** [comment]
image

**Comment by RedSparr0w** [comment]
image

**Review by schaafm — CHANGES_REQUESTED** [review]
`const votes_required = 2;`

Shouldn't this be 3?

**Review by schaafm — APPROVED** [review]

**Comment by RedSparr0w** [comment]
Oops, test amounts as I only have 2 accounts to test with lol
Updated

**Pull request merged**
